# FROM adoptopenjdk/openjdk11:alpine 

# MAINTAINER Williams santos

# RUN addgroup -S spring && adduser -S spring -G spring
# USER spring:spring
# ARG JAR_FILE=target/*.jar

# COPY ${JAR_FILE} pagamento.jar

# ENTRYPOINT ["java","-jar","/pagamento.jar"]